### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by noxtoby** [ucl-pond/pySuStaIn#1]
I get divide by zero errors relating to model likelihood, which I tracked back to missing data causing problems with `max()` and `min()`, etc. Couldn't fix it with `numpy.nanmax()`, so we probably need to devise a robust method for handling missing data.

**Comment by ayoung11** [comment]
SuStaIn doesn't handle missing data at the moment, I have an idea about one way to go about it but it needs testing first

**Comment by noxtoby** [comment]
Yeah, I had a think about how to do it without biassing the model, but it's not as straightforward as it is for the EBM.

**Comment by armaneshaghi** [comment]
I close this as we have ongoing work on missing variable analysis in SuStaIn at the POND group, to be introduced later.

**Comment by d-morrison** [comment]
Any updates on handling missing data?

**Comment by noxtoby** [comment]
@d-morrison — see [ZScoreSustainMissingData](https://github.com/ucl-pond/pySuStaIn/blob/master/pySuStaIn/ZScoreSustainMissingData.py) if using the z score model. If using mixture SustaIn, then you have to handle missing data yourself when calculating the event likelihoods that go into pySuStaIn.
