### ISSUE TITLE
SuStaIn in pymc3, and Variational Inference?

### ISSUE THREAD

**Issue by Sinha-Ujjawal** [ucl-pond/pySuStaIn#13]
Can we model SuStaIn in probabilistic modelling library like pymc3, also can we use Variational Inference instead of MCMC?

**Comment by pawij** [comment]
Hi Sinha,

Thanks for the question. Yes we could variational inference and plan to implement this in a future release. As for pymc3, I don't have any experience with it so can't comment.

Peter
