### ISSUE TITLE
Fixing controls in GMM 

### ISSUE THREAD

**Issue by 88vikram** [ucl-pond/pySuStaIn#21]
Hi Neil, Leon, Others

I am trying to use Mixture SuStaIn with fixed controls in GMM (i.e. without optimizing for the controls Gaussian) and I would like to get your opinion if what I am doing is okay.

In mixture_model/utils/fit_all_gmm_models, instead of calling the fit function, I am trying to call the fit_constrained function in gmm.py 

Is this okay ? I see that all the necessary functions are in place for making use of this functionality. Is there a reason for you to not provide access to this function through user controllable options (for e.g. if there is an unfixed bug in the fit_constrained function etc.) ? 

Do let me know.

Cheers,
Vikram

**Comment by noxtoby** [comment]
Hi Vikram,

We haven't tested `fit_constrained()` extensively, so it would be great to get your feedback.

Cheers,
Neil

**Comment by noxtoby** [comment]
Closing this as answered.
