### ISSUE TITLE
Data Preparation Pipeline/Code 

### ISSUE THREAD

**Issue by lmz123321** [ucl-pond/pySuStaIn#34]
Hi, pySuStaIn is a great work, thanks for your effort! 

I hope to use SuStaIn to subtype patients from our private Alzheimer's Disease structure MRI dataset.

However, I find it hard to implement the data preparation part (i.e. how to obtain z-scores from the raw MRI images).

Could you share your AD MRI data preparation code? or maybe provide some more detailed pipeline instructions of it? 

(I checked the instruction provided in your Nat.Comm. paper, but found it too coarse to reproduce.)

Grateful for your help.

**Comment by noxtoby** [comment]
1. Extract biomarkers from your raw MRI, e.g. regional volumes of GM tissue.
2. Identify your control group => calculate mean of controls `m` and standard deviation of controls `s` for each biomarker
3. For each biomarker `x`, calculate `z = (x - m)/s`
4. Make sure that `z` increases with progression => swap sign if necessary

**Comment by lmz123321** [comment]
Hi, sorry to bother again.

I notice, in ADNI, the control group is defined as those CN subjects with CSF Abeta 1-42 > 192 pg/ml.

I do not understand why we need the restriction of CSF Abeta 1-42 > 192 pg/ml ?

Since we currently do not have the CSF data, can we just use all CN subjects as our control groups?

Thx.

**Comment by noxtoby** [comment]
Hope this doesn't sound too brutal, but you're asking about a study design choice, not pySuStaIn. This is not the place for that.

For the record, amyloid pathology is a hallmark of Alzheimer's disease and so CN individuals with low Abeta in CSF have high Abeta in the brain and therefore may develop Alzheimer's disease.

**Comment by lmz123321** [comment]
My apologies. 

I know this is not an appropriate place to ask problems about the SuStaIn paper. I asked here only because I failed to receive any respondence from Dr. Young (both [at]ucl.ac.uk and [at]kcl.ac.uk) for about a weak. Any suggestions?
