### ISSUE TITLE
Question on Using pySuStaIn on ADNI

### ISSUE THREAD

**Issue by lmz123321** [ucl-pond/pySuStaIn#36]
Hi, Thanks for releasing pySuStaIn !

I am interested in AD pathology and currently trying to reproduce your subtyping results on ADNI dataset (i.e. the resulst reported in your Nat.Comm. 2018 paper).

I am confused of two problems:

1. Some subjects in ADNI 3T and 1.5T dataset have longitudinal data (datapoints collected at different time). So, how did you decide which datapoint to use? 
2. Can you provide the positional variance diagrams (containing all brain regions) learned by SuStaIn on ADNI 3T/1.5T dataset?  Because the qualitative results of disease progression in your paper are rather rough to understand detailed pathology.

Grateful for your help 😁

**Comment by noxtoby** [comment]
1. We used the first available ("baseline") visit for each individual.
2. I don't have the PVDs (maybe @ayoung11 does), but you should be able to reproduce them very closely using the pySuStaIn codebase and the ADNI data.

**Comment by lmz123321** [comment]
Thanks for replying. 

I note that pySuStaIn provides very good documentations, thus I believe it should be easy to use.

However, since we do not have the identical data pre-processing codes (those used to compute the z-scores), we still hope to obtain the PVDs so that we can confirm our reproduction. @ayoung11  

Thanks a lot.

**Comment by noxtoby** [comment]
I tried to explain how to calculate a z-score in [this response](https://github.com/ucl-pond/pySuStaIn/issues/34#issuecomment-1045859418) to an earlier issue you raised.

Suggest you have a go yourself.
