### ISSUE TITLE
Apply the trained model to external/independent data

### ISSUE THREAD

**Issue by anbai106** [ucl-pond/pySuStaIn#50]
Hello, 

Is it possible to apply the optimal model (after CV) to external independent data? If so, can you please add functionality to this tutorial: https://github.com/ucl-pond/pySuStaIn/blob/master/notebooks/SuStaInWorkshop.ipynb

I assume we only need to z-score the new data relative to the CN data used for the training? 

Thank you very much!

**Comment by noxtoby** [comment]
You want this function: [subtype_and_stage_new_data()](https://github.com/ucl-pond/pySuStaIn/blob/bcb7b9072123b3d1cd3779d799fdaf2776abaeba/pySuStaIn/ZscoreSustain.py#L454) which is included (albeit commented out) in the simulation notebook [here](https://github.com/ucl-pond/pySuStaIn/blob/bcb7b9072123b3d1cd3779d799fdaf2776abaeba/notebooks/SuStaIn%20tutorial%20using%20simulated%20data.ipynb#L1914)

**Comment by noxtoby** [comment]
(P.S.
Yes — your new data needs to be suitably z-scored)
