### ISSUE TITLE
About how to set the z_vals and z_max

### ISSUE THREAD

**Issue by xullllllll** [ucl-pond/pySuStaIn#60]
Dear SuStaIn friends:
  I appreciate you answering my questions about z_val last time, but I have a new problem. It is that if I set different z_vals and z_max, the subtype allocation of each sample will be different in the result, and the progress pattern recognized by the algorithm will also be different. So, I would like to ask how to set these two parameters in order to get the most reasonable subtype allocation.Looking forward to your answer.

Thank you for your help!
Xulang

**Comment by noxtoby** [comment]
Please reserve GitHub issues for technical issues with the code (including feature requests). Your question (although technical) is about modelling choices — better to send someone an email asking to collaborate.
