### ISSUE TITLE
Parallelize cross validation

### ISSUE THREAD

**Issue by Fedeanceri** [ucl-pond/pySuStaIn#64]
How do I parallelize this: CVIC, loglike_matrix = sustain_input.cross_validate_sustain_model(test_idxs). In SuStaInWorkshop.ipynb

**Comment by noxtoby** [comment]
Look at the definition of that function:
[Line 248](https://github.com/ucl-pond/pySuStaIn/blob/bcb7b9072123b3d1cd3779d799fdaf2776abaeba/pySuStaIn/AbstractSustain.py#L248)

There’s an argument called `select_folds`

**Comment by Fedeanceri** [comment]
When it runs the folds in parallel it tells me: Cannot calculate CVIC and loglike_matrix without all folds. Rerun cross_validate_sustain_model after all folds calculated.
CVIC: ([], [], [], [], [], [], [], [])
loglike_matrix: ([], [], [], [], [], [], [], [])

**Comment by noxtoby** [comment]
Looks like none of your folds have completed. The `select_folds` parameter allows you to run each fold individually, so you can send each fold to a different CPU yourself...manually...

...**the code does not run in parallel — you have to do it yourself**.

This is pretty clear from the comment in [Line 248](https://github.com/ucl-pond/pySuStaIn/blob/bcb7b9072123b3d1cd3779d799fdaf2776abaeba/pySuStaIn/AbstractSustain.py#L248).

Once you've run them all (either sequentially, or separately using `select_folds`), _and_ they've all completed, you'll be the proud owner of a pickle file containing the results for each fold. 

Then if you were to call the function again (but this time **without** the `select_folds` argument) the code will sequentially load all the pickle files and calculate CVIC for you.

**Comment by Fedeanceri** [comment]
thank you very much @noxtoby , I already got it!
